const ToC = [
  {
    "ID": "d1e35",
    "CategoryId": null,
    "DisplayName": "Front matter",
    "PMEntryType": null,
    "DMC": null,
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 0,
    "dmRef": null,
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-001A-D",
    "CategoryId": "d1e35",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-001A-D s1kd-tools-Title page",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-001A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "001", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": "Title page"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-00SA-D",
    "CategoryId": "d1e35",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-00SA-D s1kd-tools-List of effective data modules",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-00SA-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "00S", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": "List of effective data modules"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-00UA-D",
    "CategoryId": "d1e35",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-00UA-D s1kd-tools-Highlights",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-00UA-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "00U", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": "Highlights"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-009A-D",
    "CategoryId": "d1e35",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-009A-D s1kd-tools-Table of contents",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-009A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "009", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": "Table of contents"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-005A-D",
    "CategoryId": "d1e35",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-005A-D s1kd-tools-List of abbreviations",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-005A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "005", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": "List of abbreviations"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "d1e83",
    "CategoryId": null,
    "DisplayName": "Introduction",
    "PMEntryType": null,
    "DMC": null,
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 0,
    "dmRef": null,
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-040B-D",
    "CategoryId": "d1e83",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-040B-D s1kd-tools-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-040B-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "B", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-018A-D",
    "CategoryId": "d1e83",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-018A-D s1kd-tools-Introduction",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-018A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "018", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": "Introduction"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-920A-D",
    "CategoryId": "d1e83",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-920A-D s1kd-tools-Building, installing and uninstalling",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-920A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "920", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": "Building, installing and uninstalling"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-130A-D",
    "CategoryId": "d1e83",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-130A-D s1kd-tools-Usage examples",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-130A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "130", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": "Usage examples"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-014A-D",
    "CategoryId": "d1e83",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-014A-D s1kd-tools-.defaults file identifiers",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-014A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "014", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": ".defaults file identifiers"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-00-00-00-00A-C30A-D",
    "CategoryId": "d1e83",
    "DisplayName": "S1KDTOOLS-A-00-00-00-00A-C30A-D s1kd-tools-Issue compatibility",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-00-00-00-00A-C30A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "00", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "C30", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-tools"}, "InfoName": {"Text": "Issue compatibility"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "d1e140",
    "CategoryId": null,
    "DisplayName": "Tools for generating data",
    "PMEntryType": null,
    "DMC": null,
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 0,
    "dmRef": null,
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-30-00-00-00A-040A-D",
    "CategoryId": "d1e140",
    "DisplayName": "S1KDTOOLS-A-30-00-00-00A-040A-D s1kd-defaults-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-30-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "30", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-defaults"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-22-00-00-00A-040A-D",
    "CategoryId": "d1e140",
    "DisplayName": "S1KDTOOLS-A-22-00-00-00A-040A-D s1kd-dmrl-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-22-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "22", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-dmrl"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-16-00-00-00A-040A-D",
    "CategoryId": "d1e140",
    "DisplayName": "S1KDTOOLS-A-16-00-00-00A-040A-D s1kd-newcom-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-16-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "16", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-newcom"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-17-00-00-00A-040A-D",
    "CategoryId": "d1e140",
    "DisplayName": "S1KDTOOLS-A-17-00-00-00A-040A-D s1kd-newddn-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-17-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "17", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-newddn"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-07-00-00-00A-040A-D",
    "CategoryId": "d1e140",
    "DisplayName": "S1KDTOOLS-A-07-00-00-00A-040A-D s1kd-newdm-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-07-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "07", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-newdm"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-21-00-00-00A-040A-D",
    "CategoryId": "d1e140",
    "DisplayName": "S1KDTOOLS-A-21-00-00-00A-040A-D s1kd-newdml-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-21-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "21", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-newdml"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-13-00-00-00A-040A-D",
    "CategoryId": "d1e140",
    "DisplayName": "S1KDTOOLS-A-13-00-00-00A-040A-D s1kd-newimf-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-13-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "13", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-newimf"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-12-00-00-00A-040A-D",
    "CategoryId": "d1e140",
    "DisplayName": "S1KDTOOLS-A-12-00-00-00A-040A-D s1kd-newpm-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-12-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "12", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-newpm"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-35-00-00-00A-040A-D",
    "CategoryId": "d1e140",
    "DisplayName": "S1KDTOOLS-A-35-00-00-00A-040A-D s1kd-newsmc-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-35-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "35", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-newsmc"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-31-00-00-00A-040A-D",
    "CategoryId": "d1e140",
    "DisplayName": "S1KDTOOLS-A-31-00-00-00A-040A-D s1kd-newupf-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-31-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "31", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-newupf"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "d1e233",
    "CategoryId": null,
    "DisplayName": "Tools for authoring and managing data",
    "PMEntryType": null,
    "DMC": null,
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 0,
    "dmRef": null,
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-27-00-00-00A-040A-D",
    "CategoryId": "d1e233",
    "DisplayName": "S1KDTOOLS-A-27-00-00-00A-040A-D s1kd-addicn-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-27-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "27", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-addicn"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-06-00-00-00A-040A-D",
    "CategoryId": "d1e233",
    "DisplayName": "S1KDTOOLS-A-06-00-00-00A-040A-D s1kd-ls-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-06-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "06", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-ls"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-08-00-00-00A-040A-D",
    "CategoryId": "d1e233",
    "DisplayName": "S1KDTOOLS-A-08-00-00-00A-040A-D s1kd-ref-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-08-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "08", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-ref"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-09-00-00-00A-040A-D",
    "CategoryId": "d1e233",
    "DisplayName": "S1KDTOOLS-A-09-00-00-00A-040A-D s1kd-metadata-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-09-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "09", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-metadata"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-19-00-00-00A-040A-D",
    "CategoryId": "d1e233",
    "DisplayName": "S1KDTOOLS-A-19-00-00-00A-040A-D s1kd-mvref-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-19-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "19", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-mvref"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-34-00-00-00A-040A-D",
    "CategoryId": "d1e233",
    "DisplayName": "S1KDTOOLS-A-34-00-00-00A-040A-D s1kd-sns-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-34-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "34", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-sns"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-05-00-00-00A-040A-D",
    "CategoryId": "d1e233",
    "DisplayName": "S1KDTOOLS-A-05-00-00-00A-040A-D s1kd-upissue-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-05-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "05", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-upissue"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "d1e299",
    "CategoryId": null,
    "DisplayName": "Tools for validating data",
    "PMEntryType": null,
    "DMC": null,
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 0,
    "dmRef": null,
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-11-00-00-00A-040A-D",
    "CategoryId": "d1e299",
    "DisplayName": "S1KDTOOLS-A-11-00-00-00A-040A-D s1kd-appcheck-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-11-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "11", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-appcheck"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-04-00-00-00A-040A-D",
    "CategoryId": "d1e299",
    "DisplayName": "S1KDTOOLS-A-04-00-00-00A-040A-D s1kd-brexcheck-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-04-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "04", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-brexcheck"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-25-00-00-00A-040A-D",
    "CategoryId": "d1e299",
    "DisplayName": "S1KDTOOLS-A-25-00-00-00A-040A-D s1kd-refs-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-25-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "25", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-refs"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-18-00-00-00A-040A-D",
    "CategoryId": "d1e299",
    "DisplayName": "S1KDTOOLS-A-18-00-00-00A-040A-D s1kd-repcheck-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-18-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "18", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-repcheck"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-02-00-00-00A-040A-D",
    "CategoryId": "d1e299",
    "DisplayName": "S1KDTOOLS-A-02-00-00-00A-040A-D s1kd-validate-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-02-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "02", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-validate"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "d1e347",
    "CategoryId": null,
    "DisplayName": "Tools for delivering data",
    "PMEntryType": null,
    "DMC": null,
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 0,
    "dmRef": null,
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-20-00-00-00A-040A-D",
    "CategoryId": "d1e347",
    "DisplayName": "S1KDTOOLS-A-20-00-00-00A-040A-D s1kd-acronyms-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-20-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "20", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-acronyms"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-26-00-00-00A-040A-D",
    "CategoryId": "d1e347",
    "DisplayName": "S1KDTOOLS-A-26-00-00-00A-040A-D s1kd-aspp-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-26-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "26", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-aspp"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-23-00-00-00A-040A-D",
    "CategoryId": "d1e347",
    "DisplayName": "S1KDTOOLS-A-23-00-00-00A-040A-D s1kd-flatten-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-23-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "23", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-flatten"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-33-00-00-00A-040A-D",
    "CategoryId": "d1e347",
    "DisplayName": "S1KDTOOLS-A-33-00-00-00A-040A-D s1kd-fmgen-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-33-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "33", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-fmgen"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-32-00-00-00A-040A-D",
    "CategoryId": "d1e347",
    "DisplayName": "S1KDTOOLS-A-32-00-00-00A-040A-D s1kd-icncatalog-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-32-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "32", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-icncatalog"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-28-00-00-00A-040A-D",
    "CategoryId": "d1e347",
    "DisplayName": "S1KDTOOLS-A-28-00-00-00A-040A-D s1kd-index-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-28-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "28", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-index"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-03-00-00-00A-040A-D",
    "CategoryId": "d1e347",
    "DisplayName": "S1KDTOOLS-A-03-00-00-00A-040A-D s1kd-instance-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-03-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "03", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-instance"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-14-00-00-00A-040A-D",
    "CategoryId": "d1e347",
    "DisplayName": "S1KDTOOLS-A-14-00-00-00A-040A-D s1kd-neutralize-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-14-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "14", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-neutralize"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-01-00-00-00A-040A-D",
    "CategoryId": "d1e347",
    "DisplayName": "S1KDTOOLS-A-01-00-00-00A-040A-D s1kd-syncrefs-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-01-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "01", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-syncrefs"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  },
  {
    "ID": "DMC-S1KDTOOLS-A-10-00-00-00A-040A-D",
    "CategoryId": "d1e347",
    "DisplayName": "S1KDTOOLS-A-10-00-00-00A-040A-D s1kd-uom-Description",
    "PMEntryType": null,
    "DMC": "S1KDTOOLS-A-10-00-00-00A-040A-D",
    "AddedNew": false,
    "dmIdUpissued": false,
    "dmId": 0,
    "pmId": 0,
    "expanded": false,
    "Type": 1,
    "dmRef": {"DmRefIdent": {"DmCode": {"ModelIdentCode": "S1KDTOOLS", "SystemDiffCode": "A", "SystemCode": "10", "SubSystemCode": "0", "SubSubSystemCode": "0", "AssyCode": "00", "DisassyCode": "00", "DisassyCodeVariant": "A", "InfoCode": "040", "InfoCodeVariant": "A", "ItemLocationCode": "D"}, "IssueInfo": null, "Language": null}, "DmRefAddressItems": {"DmTitle": {"TechName": {"Text": "s1kd-uom"}, "InfoName": {"Text": "Description"}}, "IssueDate": null}, "ApplicRefId": null},
    "pmRefs": null,
    "Children": []
  }
];

module.exports = ToC;